# Metadados da API no Swagger UI
mp.openapi.extensions.smallrye.info.title=Code with Quarkus API
mp.openapi.extensions.smallrye.info.version=1.0.0
mp.openapi.extensions.smallrye.info.description=API de estudos Quarkus

# Incluir Swagger UI também em build de producao (padrao: so em dev)
# quarkus.swagger-ui.always-include=true

# Configuracao do banco H2 (memoria)
quarkus.datasource.db-kind=h2
quarkus.datasource.username=sa
quarkus.datasource.password=sa
quarkus.datasource.jdbc.url=jdbc:h2:mem:pessoas;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE

# Hibernate ORM
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=true

# Console H2 (disponivel em dev: http://localhost:8080/h2)
quarkus.h2.console.enabled=true

