# Metadados da API no Swagger UI
mp.openapi.extensions.smallrye.info.title=Code with Quarkus API
mp.openapi.extensions.smallrye.info.version=1.0.0
mp.openapi.extensions.smallrye.info.description=API de estudos Quarkus

# Incluir Swagger UI também em build de producao (padrao: so em dev)
# quarkus.swagger-ui.always-include=true
