spring:
  application:
    name: java-ai-engineering-specialization
  ai:
    ollama:
    base-url: http://localhost:11434
    connection-timeout: 60s
    read-timeout: 60s
    chat:
      model: gemma3:4b
      num-ctx: 4096
      temperature: 0.2
